[project]
name = "gists"
version = "0.1.0"
description = "Collection of scripts."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.0.0",
    "pytest>=8.3.3",
    "requests>=2.32.3",
]

[project.scripts]
webp-converter = "webp_converter.webp_converter"
